### ISSUE TITLE
Investigate session timeouts under concurrent loads

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb-client-python#226]
Note to myself or @alexjpwalker  to investigate example of session timeout.

The issue is that sessions appear to timeout sometimes when concurrently querying or loading data, which causes the  application to crash unless it handles random session failures.

**Comment by alexjpwalker** [comment]
another report: https://forum.vaticle.com/t/migration-error-in-typedb-data-bio-covid/2659

**Comment by alexjpwalker** [comment]
@flyingsilverfin This should be fixed by changes made on the server side, right?

**Comment by flyingsilverfin** [comment]
it should be!
