### ISSUE TITLE
Create an instance from a Type always give back the same iid

### ISSUE THREAD

**Issue by PatLechevallier** [vaticle/typedb-client-python#242]
## Description

entity_instance = entity_type.as_remote(tx).create()

The instance of entity or relation (not tested from the other relation) has always the same iid.

## Environment

1. MacOS
2. TypeDB version (and platform): typedb-all-mac-2.5.0
3. TypeDB client-python version: typedb-client==2.5.0, typedb-protocol==2.5.0
4. Python version: Python 3.8.2 64-bit
4. Other environment details:
locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

^No idea if it's relevant, My settings for the encoding format

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. product sub entity;
2. ```with TypeDB.core_client("localhost:1729") as client:
        with client.session("test", SessionType.DATA) as session:
            with session.transaction(TransactionType.WRITE) as write_transaction:
                product_type = write_transaction.concepts().get_entity_type("product")
                product_instance = product_type.as_remote(write_transaction).create() #Create the product
                print("Product Instance IID", product_instance.get_iid())
                write_transaction.commit()
      with TypeDB.core_client("localhost:1729") as client:
        with client.session("test", SessionType.DATA) as session:
            with session.transaction(TransactionType.READ) as read_transaction:
                print(product_instance,product_instance.get_iid())
                thing = read_transaction.concepts().get_thing(product_instance.get_iid())
                print(thing)```

## Expected Output

Expect to have the real iid from the server?

## Actual Output

ALways the same iid with a trail of ffffffff (first instance created from a concept)
 
## Additional information

Seems to work well with 
`with TypeDB.core_client("localhost:1729") as client:
    with client.session("social_network", SessionType.DATA) as session:
        ## Insert a Person using a WRITE transaction
        with session.transaction(TransactionType.WRITE) as write_transaction:
            insert_iterator = write_transaction.query().insert('insert $x isa person, has email "x@email.com";')
            concepts = [ans.get("x") for ans in insert_iterator]
            print("Inserted a person with ID: {0}".format(concepts[0].get_iid()))
            ## to persist changes, write`

**Comment by PatLechevallier** [comment]
It's not a bug, since the concept is not committed. It is not the persistent iid.
The only way to get the real create resource is to create your own key id system.

It should be nice to have access to that though.

**Comment by alexjpwalker** [comment]
Thanks for the report!

Indeed the IID returned before a transaction is committed is nonsense. We encourage the use of `@key` attributes to uniquely identify Concepts (in general, not just in uncommitted transactions!) The IID stands for Internal ID and is not intended for general use.
