### ISSUE TITLE
Support Python 3.11 By Bumping grpcio tools

### ISSUE THREAD

**Issue by thomaschristopherking** [vaticle/typedb-client-python#269]
## Problem to Solve

Support Python 3.11, currently using a version of grpcio tools that does not support python 3.11

## Current Workaround

Use an older version of Python

## Proposed Solution

Bump grpcio tools from 1.38 to 1.50 - See this closed ticket for when python 3.11 was supported: https://github.com/grpc/grpc/issues/30445

## Additional Information

Trying to install on python 3.11 causes this error:
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by alexjpwalker** [comment]
Fixed in:

- #275
