### ISSUE TITLE
GCP and protobuf requirement updates

### ISSUE THREAD

**Issue by LeData** [vaticle/typedb-client-python#270]
## Description

The client currently pins the protobuf library to version 3.15, which results in compatibility issues with google.storage clients.
Though there is no requirement problems, error messages result from importing the library:
```
Traceback (most recent call last):
  File "xxx", line 10, in <module>
    from google.cloud import storage
...
...
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

## Environment

1. TypeDB client-python version: 2.12.0
4. Python version: 3.9
4. Other environment details: google_cloud_storage = 2.6.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. build an environment with the typedb client and google_cloud_storage from above
2. load `google.cloud.storage`.

## Expected Output

I expected the libraries to load without a problem, but it seems that this is a known issue with google and protobuf < 3.20.1

## Actual Output

The error message from above
 
## Additional information

https://github.com/googleapis/python-iam/issues/185

**Comment by LeData** [comment]
That does the trick, thank you!

**Comment by jamesreprise** [comment]
Excellent! Closing.
