### ISSUE TITLE
Cluster server client: stub creation depends on stub

### ISSUE THREAD

**Issue by dmitrii-ubskii** [vaticle/typedb-client-python#273]
## Description

Potential circular dependency in https://github.com/vaticle/typedb-client-python/blob/master/typedb/connection/cluster/server_client.py.

The constructor of  `_ClusterServerClient` calls `_ClusterServerClient.new_channel_and_stub()` during creation of the channel and the gRPC `_stub` of a server client (L36), 
which calls `_ClusterServerClient._new_channel()` (L49),
which references a yet-not-created `self._stub` in a lambda that it passes to `grpc.metadata_call_credentials()` (L60),
which, if it calls the lambda at that point, correctly raises `AttributeError: '_ClusterServerClient' object has no attribute '_stub'`.

**Comment by alexjpwalker** [comment]
Hopefully this issue will dissolve when we call Rust via FFI.
