### ISSUE TITLE
Failure to insert relations with core 1.5.6

### ISSUE THREAD

**Issue by glarsen** [vaticle/typedb-client-python#50]
## Description

Upgrade incompatibility: The same codebase targeting Core 1.5.3 inserts relations correctly but fails to do so when targeting Core 1.5.6.

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04 LTS in Docker
2. Grakn version (and platform): Grakn Core 1.5.6
3. Grakn client-python version: client-python 1.5.3
4. Python version: 3.7
4. Other environment details: Docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Insert entities
2. Insert relations between entities
3. Query for relations (via console or workbase)
4. Error: Query finds no relations

## Expected Output

Both entities and relations are inserted.

## Actual Output

Entities and their attributes are inserted but no relations are inserted.
 
## Additional information

No errors are shown in the server logs. No stack-traces occur client-side.

**Comment by vmax** [comment]
@glarsen thank you for reporting the issue! To help us debug and figure out the core reason, could you reproducing it on latest versions of Grakn (1.6.1) and Grakn Client Python (1.6.0)?

**Comment by alexjpwalker** [comment]
We now have extensive test coverage for inserting relations via client-python, so I'm marking this issue as resolved. Please feel free to reopen should the issue still occur in TypeDB.
