### ISSUE TITLE
Python client leaks threads on failed queries

### ISSUE THREAD

**Issue by Winawer** [vaticle/typedb-client-python#58]
## Description

When using the Python client to do bulk inserts, I've found that the client is leaking threads (enough that it inevitably crashes the client when the dataset is large enough, i.e. more than a few hundred records).  I believe this has to do something with the way I was inserting, which was to catch exceptions when I was adding an entity that had already been added before; due to the way the data I've been given is structured, I was content to eat the cost of discarding duplicate inserts by catching exceptions, but it blows up every time I try it.  

## Environment

1. OS (where Grakn server runs): OS X 10.14.5
2. Grakn version (and platform): Grakn Core 1.5.7
3. Grakn client-python version: client-python 1.5.3
4. Python version: 3.7.4

## Reproducible Steps

This is the inner loop of the code I'm writing (based off of the python phone_calls example):

```  

    with GraknClient(uri=f"{host}:{port}") as client:
        for section_name in config.csv_inputs:
            section = config.csv_inputs[section_name]
            path = os.path.join(data_dir,section.file)
            with client.session(keyspace=config.grakn.keyspace) as session:
                items = parse_data_to_dictionaries(path)

                for item in items:
                    # This is the same structure as the example, funcs returning query strings; 
                    # I'm just returning a list instead of a single query because I have a more 
                    # complex data structure.
                    graql_insert_queries = templates[section.template](item,section)

                    for query in graql_insert_queries:
                        with session.transaction().write() as transaction:                            
                            try:
                                transaction.query(query)
                                transaction.commit()
                            except GraknError as e:
                                print(f"Query failed: {e}")
```

I track the threads using `ps M <pid> | wc -l`.  When the queries are not failing the thread count remains steady at the same number of threads as cores;  after a few hundred/thousand failed queries, the thread count balloons into the thousands and the python client gives up with `cannot create new thread`.

## Output

This is the error that gets thrown when it runs out of threads:

```
Traceback (most recent call last):
  File "cli.py", line 64, in <module>
    data_loader()
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 51, in data_loader
    with session.transaction().write() as transaction:                            
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/grakn/client.py", line 106, in write
    transaction_service = TransactionService(self._session_id, _TxType.WRITE, self._transaction_rpc_constructor)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 35, in __init__
    self._communicator = Communicator(transaction_endpoint)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 133, in __init__
    self._response_iterator = grpc_stream_constructor(self)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/grpc/_channel.py", line 683, in __call__
    self._request_serializer, event_handler)
  File "/Users/XXX/Envs/XXX/lib/python3.7/site-packages/grpc/_channel.py", line 248, in _consume_request_iterator
    consumption_thread.start()
  File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 107, in grpc._cython.cygrpc.ForkManagedThread.start
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by flyingsilverfin** [comment]
Hi - could you also post the larger piece of code that spawns processes that calls the inner loop code provided above?

Thanks!

**Comment by Winawer** [comment]
@flyingsilverfin Unfortunately, I can't;  it's a real world example that includes proprietary config and data that I can't share. The loop above, though, is part of a CLI app built with Click.  As far as processes go, there's only one process so it's not multiprocessing.

**Comment by flyingsilverfin** [comment]
This is interesting - I haven't seen this threading error before, although it seems like it's a python bug rather than on our end... somehow the try/except isn't killing your threads eventually? Do you mind trying the following minor adjustment:
```
or query in graql_insert_queries:
                        with session.transaction().write() as transaction:                            
                            try:
                                transaction.query(query)
                                transaction.commit()
                            except GraknError as e:
                                print(f"Query failed: {e}")

**Comment by alexjpwalker** [comment]
We should verify that failing queries do not leak threads in TypeDB.

**Comment by haikalpribadi** [comment]
This issue is too old now. We've rewritten Grakn (and called it TypeDB) since then, and we've rewritten the python client too. I'll close this issue now as I don't believe this issue exists in the new distribution.
